apiVersion: batch/v1
kind: Job
metadata:
   name: myjob
spec:
   completions: 5
   parallelism: 2
   template:
     spec:
         containers:
           - image: busybox
             name: mycont
             command: ["sh", "-c", "echo 'hello' "]
         restartPolicy: OnFailure
