apiVersion: batch/v1
kind: CronJob
metadata:
   name: mycj
spec:
   schedule: "*/1 * * * *"
   jobTemplate:
     spec:
        template:
          metadata:
            labels:
             app: myapp
          spec:
                restartPolicy: OnFailure
               # restartPolicy: Never 
                containers:
                 - image: luksa/batch-job
                   name: mycont
