apiVersion: apps/v1
kind: Deployment
metadata:
     name: mydeploy
spec:
    replicas: 3
    selector: 
       matchLabels:
#         labels:
            env: deploy
    template:
       metadata:
         labels:
            env: deploy
       spec:
           containers:
             - name: contdeploy
               image: nginx
               ports:
                 - containerPort: 80
