apiVersion: v1
kind: ReplicationController
metadata:
    name: myrc
spec: 
   replicas: 3
   template: 
     metadata:
        labels:
           enc: prod
     spec: 
       containers:
          - image: nginx
            name: mynginx
            ports:
              - containerPort: 80
            livenessProbe:
              httpGet:
                path: index.html
                port: 80

