
apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  namespace: myns2  
spec:
   containers:
     - image: nginx
       ports:
         - containerPort: 80
           hostPort: 80
       name: mynginx
