apiVersion: v1
kind: Pod
metadata:
     name: mydbpod1
spec:
    containers:
       - name: mydbcont
         image: mysql
         ports:
            - containerPort: 80
         env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                 secretKeyRef: 
                      name: mysecret
                      key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "mydb"
