apiVersion: v1
kind: Pod
metadata:
  name: mydbpod
spec:
   containers:
     - image: mysql
       ports:
         - containerPort: 3306
       name: mycont
       env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             configMapKeyRef:
                name: mysql-pass
                key: MYSQL_ROOT_PASSWORD
         - name: MYSQL_DATABASE
           value: "mydb"
