apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeploy
spec:
   replicas: 3
   selector: 
      matchLabels:
            env: test
   template:
      metadata:
         labels:
            env: test
      spec:
          containers:
              - image: nginx
                name: mycont
                ports:
                 -  containerPort: 80
                volumeMounts:
                    - name: myvolume
                      mountPath: /usr/share/nginx/html
          volumes:
             - name: myvolume
               hostPath:
                     path: /home/ubuntu/mydata
                     type: Directory             
