apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: my-rs
spec:
    replicas: 3
    selector:
       matchLabels:
         app: web
    template:
      metadata:
         labels:
           app: web
      spec:
         containers:
           - name: rs-cont
             image: nginx
             ports:
               - containerPort: 80 
