apiVersion: v1
kind: ReplicationController
metadata:
    name: my-rc
spec:
    replicas: 3
    selector:
       app: web
    template:
       metadata:
          labels: 
           app: web
       spec:
         containers:
           - name: my-rc-cont
             image: nginx
             ports:
              - containerPort: 80 
