apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
  namespace: ns-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx

    
